apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yourapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:y16me91o/app-repo.git
    targetRevision: main
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: yourapp
  syncPolicy:
    syncOptions:
    - CreateNameSpace=true
    automated:
      selfHeal: true
      prune: true
