apiVersion: apps/v1
kind: Deployment
metadata:
  name: yourapp
  namespace: yourapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yourapp
  template:
    metadata:
      labels:
        app: yourapp
    spec:
      containers:
        - name: yourapp
          image: y16me910/yourapp:46
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: '3000'

